# Generated by Django 3.0.12 on 2021-03-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=140)),
                ('last_name', models.TextField(max_length=140)),
            ],
        ),
    ]
