# Generated by Django 3.0.12 on 2021-03-23 00:44

from django.db import migrations, models


def hello_world(*args, **kwargs):
    print("hello world!")


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(hello_world, migrations.RunPython.noop),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='default@fake.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.TextField(max_length=50),
        ),
    ]
